Update sentences.js
luizae/tindev.guru pull request #17
Opened 2021-06-08 22:11 UTC by dandankara

2021-06-08 22:14 UTC, luizae approved these changes

2021-06-08 22:15 UTC, imakecodes requested changes

2021-06-08 22:15 UTC, imakecodes commented on src/data/sentences.js
> +  'Você não é orientada a objetos mais é cheio de classe',
typo: usar mas e não mais, mais é soma :P

2021-06-08 22:15 UTC, imakecodes commented on src/data/sentences.js
> +  'Você não é orientada a objetos mais é cheio de classe',
não seria: cheia de classe em vez de cheio de classe?

2021-06-08 23:21 UTC, imakecodes commented on src/data/sentences.js
> +  'Nem a placa de vídeo mas potente pode renderizar toda a sua beleza',
Aqui continua "mais"

2021-06-08 23:21 UTC, imakecodes commented on src/data/sentences.js
> +  'Você não é orientada a objetos mais é cheia de classe',
Aqui em vez de `mais` é `mas`

2021-06-09 01:50 UTC, imakecodes approved these changes

2021-06-09 01:59 UTC, merged